### ISSUE TITLE
Clarification of licensing details

### ISSUE THREAD

**Issue by galenide** [softdorothy/glider_4#1]
@softdorothy The publication of the Glider 4.0 source code is of interest. At the same time, it appears that there are some licensing details that would be useful to clarify. (Ideally, the `README.md` file for Glider 4.0 could be adjusted accordingly.)

1. The `LICENSE` file contains the MIT License. Does this license only apply to the Glider 4.0 source code, or does it also apply to the Glider 4.0 icons, graphics, sounds, music, and resources in files such as `Glider.r`, `B&W Art.bin`, and `Color Art.bin` and the files in the `Glider_Sound_Files` directory?

2. From what one remembers, the Glider 4.0 game incorporated sound code from Patrick Buckland. (Looking at the sources, it is possible that the `SMS.p`, `SMSCore.a.o`, and `sms.a.o` files may relate to this code. The latter two files may be precompiled libraries.) If third-party sound code is included, then it would be useful to clarify as to how it is licensed.

3. The third-party credits for Glider PRO mention a picture of the character Ozma of Oz that came from a John R. Neill illustration in the story [Ozma of Oz](https://www.gutenberg.org/files/33361/33361-h/33361-h.htm). It appears that a similar image of Ozma is included in Glider 4.0.

**Comment by softdorothy** [comment]
I know very little about the various licenses and licensing. Sorry.

I assumed the art, sounds an resources would fall under the same license as the sources. I do not own the rights to either Patrick's code or the Ozma illustration of course.
